feat: support testing on bun
ipfs-examples/test-ipfs-example pull request #18
Opened 2024-02-08 14:54 UTC by achingbrain

Run node tests with bun using env var `NODE_EXEC=bun`

2024-02-08 15:31 UTC, achingbrain commented
Bah, it's broken on Windows, support might be added in a week or so - https://twitter.com/bunjavascript/status/1753267105909416079

2024-02-08 17:36 UTC, SgtPooki approved these changes
~good with this. Do we want to wait and see on bun+windows before merge?~

we should wait on this until bun+windows.. https://github.com/ipfs-examples/test-ipfs-example/actions/runs/7831891366/job/21369332451?pr=18

2024-04-09 17:24 UTC, salieflewis commented
> ~good with this. Do we want to wait and see on bun+windows before merge?~
> 
> we should wait on this until bun+windows.. https://github.com/ipfs-examples/test-ipfs-example/actions/runs/7831891366/job/21369332451?pr=18

Bun supports Windows 10 and later as of 1.1

https://bun.sh/blog/bun-v1.1

2024-04-09 21:38 UTC, SgtPooki requested changes

2024-04-09 21:38 UTC, SgtPooki commented on test/bun.spec.ts
> +  }
```suggestion
```

2024-04-15 16:06 UTC, SgtPooki commented on test/bun.spec.ts
> +  }
testing changes in https://github.com/ipfs-examples/test-ipfs-example/pull/19

2024-04-23 07:36 UTC, merged